# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 17e466e9e23703922688d71324815a115bdca00d5d9c4216531373ac95061e1e20aac6eb7c2682204e7a63b3cf9ab9bef21e07799419cff1dbc629d434247a90

test:
  secret_key_base: 58f8e39e7ce8c01ddcd818c5a6496abf5315e03493f541648f228f4838a90da9fba51203880d3bb644562c605009e7aee4cd6efb862807726990b2c483895ce0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
